package com.java.micarro;

import android.graphics.Color;

public class Constantes {

    public static final int AMARILLO = Color.rgb(255, 255, 0);
    public static final int VERDE = Color.rgb(60, 220, 78);
    public static final int ROJO = Color.rgb(255, 0, 0);

    public static final String SHARED_LOGIN_DATA = "shared_login_data";
    public static final String DATO_01 = "dato01";
    public static final String ESPACIO_VACIO = "";
    public static final String ESPACIO_BLACO = " ";
    public static final String ESPACIO_VACIO_DOS_PUNTOS = " : ";
    public static final String ESPACIO_VACIO_BARRA_VERTICAL = " | ";
    public static final String PERSONA = "Persona";
    public static final String ACTUALIZAR_KILOMETRAJE = "actualizarKilometraje";
    public static final String SI = "SI";
    public static final String NO = "NO";
    public static final String CONTRASENA_10_DIGITOS = "Longitud de contraseña 10 dígitos";
    public static final String CONTRASENA_INCORRECTA = "Usuario o Contraseña Incorrectos.";
    public static final String BIENVENIDO = "Bienvenido: ";
    public static final String REQUIRED = "Required";
    public static final String AGREGADO = "Agregado";
    public static final String ACTUALIZADO = "Actualizado";
    public static final String ELIMINADO = "Eliminado";
    public static final String CERO = "0";
    public static final String CONSUMO = "Consumo";
    public static final String ACEITE_BANDERA = "A";
    public static final String GASOLINA_BANDERA = "G";
    public static final String LLANTAS_BANDERA = "L";
    public static final String BATERIA_BANDERA = "B";
    public static final String ELECTRICIDAD_BANDERA = "E";
    public static final String GRAFICO_CONSUMIBLES = "Gráfico Consumibles";
    public static final String ELECTRICIDAD = "Electricidad";
    public static final String ACEITE = "Aceite";
    public static final String GASOLINA = "Gasolina";
    public static final String LLANTAS = "Llantas";
    public static final String BATERIA = "Batería";
    public static final String RECORRIDO = "RECORRIDO";
    public static final String RECORRIDO_FROND = "Recorrido: ";
    public static final String SIGNO_PORCENTAJE = " %";
    public static final String KM = " km.";
    public static final String MANTENIMIENTO_NECESARIO = "Revise sus consumibles: ";
    public static final String USTED_YA_REALIZO_EL_CAMBIO_SI_NO_EL_COSTO_DEL_CAMBIO_FUE = "Dírijase a la pantalla de CONSUMIBLES";
    public static final String ESPECIFICACIONES = "Especificaciones";
    public static final String AUTO_PRINCIPAL = "Auto Principal";
    public static final String RECORDATORIOS = "Recordatorios";
    public static final String GASTOS = "Gastos";
    public static final String DETALLE_CONSUMOS = "Detalle Consumos";
    public static final String TALLERES_AUTORIZADOS = "Talleres Autorizados";
    public static final String CHANNEL_ID = "NOTIFICACION";
    public static final int NOTIFICACION_ID = 0;
    public static final String PLACA = "Placa: ";
    public static final String MARCA = "Marca: ";
    public static final String MODELO = "Modelo: ";
    public static final String ULTIMO_KILOMETRAJE = "Último Kilometraje: ";
    public static final String KILOMETRAJE_INGRESADO_DEBE_SER_MAYOR_AL_REGISTRADO = "El kilometraje ingresado debe ser mayor al registrado: ";
    public static final String NOTIFICACION = "Notificación";
    public static final String REALIZO_MANTENIMIENTO_RESPECTIVO = "Usted ya realizó el mantenimiento respectivo:";
    public static final String REVISAR_CONSUMIBLES = "Revise sus consumibles:";
    public static final String INGRESE_CONSUMO = "Ingrese el consumo $:";
    public static final String ACEPTAR = "Aceptar";
    public static final String KILOMETRAJE_EN_CERO = "Kilometraje en cero";

    public static final String CONTADOR_ACEITE = "Contador_Aceite";
    public static final String CONTADOR_GASOLINA = "Contador_Gasolina";
    public static final String CONTADOR_LLANTAS = "Contador_Llantas";
    public static final String CONTADOR_ELECTRICIDAD = "Contador_Electricidad";
    public static final String CONTADOR_BATERIA = "Contador_Bateria";

    public static final String INGRESAR_UN_EMAIL = "Se debe ingresar un email";
    public static final String INGRESAR_UNA_PASSWORD = "Se debe ingresar una contraseña";
    public static final String REGISTRO_EN_LINEA = "Realizando registro en línea ...";
    public static final String CONSULTA_EN_LINEA = "Realizando consulta en línea ...";
    public static final String USUARIO_NO_EXISTE = "Ese usuario no existe: ";
    public static final String INGRESAR_UNA_IDENTIFICACION = "Se debe ingresar una identificación.";
    public static final String INGRESAR_UN_NOMBRE = "Se debe ingresar un nombre.";
    public static final String INGRESAR_UN_APELLIDO = "Se debe ingresar un apellido.";
    public static final String INGRESAR_UN_TELEFONO = "Se debe ingresar un número de télefono.";
    public static final String INGRESAR_UNA_PLACA = "Se debe ingresar una placa.";
    public static final String INGRESAR_UNA_MARCA = "Se deb ingresar una marca.";
    public static final String INGRESAR_UN_MODELO = "Se debe ingresar un modelo.";
    public static final String INGRESAR_UN_KILOMETRAJE = "Se debe ingresar un kilometraje.";
    public static final String VERIFIQUE_CORREO = "Verifique su correo.";

    public static final String IDENTIFICACION_SESION = "ideSes";
    public static final String KILOMETRAJE_SESION = "KilSes";
    public static final String NOMBRE_SESION = "nomSes";
    public static final String APELLIDO_SESION = "apeSes";
    public static final String TELEFONO_SESION = "telSes";
    public static final String CORREO_SESION = "corSes";
    public static final String PLACA_SESION = "plaSes";
    public static final String MARCA_SESION = "marSes";
    public static final String MODELO_SESION = "modSes";
    public static final String KILOMETRAJE_ACEITE_SESION = "kilAceSes";
    public static final String KILOMETRAJE_BATERIA_SESION = "kilBatSes";
    public static final String KILOMETRAJE_ELECTRICIDAD_SESION = "kilEleSes";
    public static final String KILOMETRAJE_GASOLINA_SESION = "kilGasSes";
    public static final String KILOMETRAJE_LLANTAS_SESION = "kilLlaSes";
}
